export const tracks = [
    {
        name: 'Albert Park Circuit',
        country: 'Australia',
        city: 'Melbourne',
        length: 5.278,
        numberOfLaps: 58,
        numberOfTurns: 14,
        recordTime: '1:19.813',
        recordDriver: 'Charles Leclerc',
        recordYear: 2024,
        image: '1.jpg'
    },
    {
        name: 'Shanghai International Circuit',
        country: 'China',
        city: 'Shanghai',
        length: 5.451,
        numberOfLaps: 56,
        numberOfTurns: 16,
        recordTime: '1:34.742',
        recordDriver: 'Pierre Gasly',
        recordYear: 2019,
        image: '2.jpg'
    },
    {
        name: 'Suzuka Circuit',
        country: 'Japan',
        city: 'Suzuka',
        length: 5.807,
        numberOfLaps: 53,
        numberOfTurns: 18,
        recordTime: '1:30.965',
        recordDriver: 'Kimi Raikkonen',
        recordYear: 2005,
        image: '3.jpg'
    },
    {
        name: 'Bahrain International Circuit',
        country: 'Bahrain',
        city: 'Sakhir',
        length: 5.412,
        numberOfLaps: 57,
        numberOfTurns: 15,
        recordTime: '1:32.014',
        recordDriver: 'Max Verstappen',
        recordYear: 2020,
        image: '4.jpg'
    },
    {
        name: 'Jeddah Corniche Circuit',
        country: 'Saudi Arabia',
        city: 'Jeddah',
        length: 6.174,
        numberOfLaps: 50,
        numberOfTurns: 27,
        recordTime: '1:30.734',
        recordDriver: 'Lewis Hamilton',
        recordYear: 2021,
        image: '5.jpg'
    },
    {
        name: 'Miami International Autodrome',
        country: 'USA',
        city: 'Miami',
        length: 5.412,
        numberOfLaps: 57,
        numberOfTurns: 19,
        recordTime: '1:28.708',
        recordDriver: 'Max Verstappen',
        recordYear: 2023,
        image: '6.jpg'
    },
    {
        name: 'Imola (Autodromo Enzo e Dino Ferrari)',
        country: 'Italy',
        city: 'Imola',
        length: 4.909,
        numberOfLaps: 63,
        numberOfTurns: 19,
        recordTime: '1:18.451',
        recordDriver: 'Lewis Hamilton',
        recordYear: 2020,
        image: '7.jpg'
    },
    {
        name: 'Circuit de Monaco',
        country: 'Monaco',
        city: 'Monte Carlo',
        length: 3.337,
        numberOfLaps: 78,
        numberOfTurns: 19,
        recordTime: '1:12.909',
        recordDriver: 'Lewis Hamilton',
        recordYear: 2021,
        image: '8.jpg'
    },
    {
        name: 'Circuit de Catalunya',
        country: 'Spain',
        city: 'Barcelona',
        length: 4.657,
        numberOfLaps: 66,
        numberOfTurns: 16,
        recordTime: '1:15.743',
        recordDriver: 'Oscar Piastri',
        recordYear: 2025,
        image: '9.jpg'
    },
    {
        name: 'Circuit Gilles Villeneuve',
        country: 'Canada',
        city: 'Montreal',
        length: 4.361,
        numberOfLaps: 70,
        numberOfTurns: 14,
        recordTime: '1:13.078',
        recordDriver: 'Valtteri Bottas',
        recordYear: 2019,
        image: '10.jpg'
    },
    {
        name: 'Red Bull Ring',
        country: 'Austria',
        city: 'Spielberg',
        length: 4.326,
        numberOfLaps: 71,
        numberOfTurns: 10,
        recordTime: '1:07.924',
        recordDriver: 'Oscar Piastri',
        recordYear: 2025,
        image: '11.jpg'
    },
    {
        name: 'Silverstone Circuit',
        country: 'United Kingdom',
        city: 'Silverstone',
        length: 5.891,
        numberOfLaps: 52,
        numberOfTurns: 18,
        recordTime: '1:27.097',
        recordDriver: 'Max Verstappen',
        recordYear: 2020,
        image: '12.jpg'
    },
    {
        name: 'Circuit de Spa-Francorchamps',
        country: 'Belgium',
        city: 'Spa',
        length: 7.004,
        numberOfLaps: 44,
        numberOfTurns: 19,
        recordTime: '1:46.250',
        recordDriver: 'Sergio Perez',
        recordYear: 2024,
        image: '13.jpg'
    },
    {
        name: 'Hungaroring',
        country: 'Hungary',
        city: 'Budapest',
        length: 4.381,
        numberOfLaps: 70,
        numberOfTurns: 14,
        recordTime: '1:16.627',
        recordDriver: 'Lewis Hamilton',
        recordYear: 2020,
        image: '14.jpg'
    },
    {
        name: 'Circuit Zandvoort',
        country: 'Netherlands',
        city: 'Zandvoort',
        length: 4.259,
        numberOfLaps: 72,
        numberOfTurns: 14,
        recordTime: '1:11.097',
        recordDriver: 'Lewis Hamilton',
        recordYear: 2021,
        image: '15.jpg'
    },
    {
        name: 'Autodromo Nazionale Monza',
        country: 'Italy',
        city: 'Monza',
        length: 5.793,
        numberOfLaps: 53,
        numberOfTurns: 11,
        recordTime: '1:20.901',
        recordDriver: 'Lando Norris',
        recordYear: 2025,
        image: '16.jpg'
    },
    {
        name: 'Baku City Circuit',
        country: 'Azerbaijan',
        city: 'Baku',
        length: 6.003,
        numberOfLaps: 51,
        numberOfTurns: 20,
        recordTime: '1:43.009',
        recordDriver: 'Charles Leclerc',
        recordYear: 2019,
        image: '17.jpg'
    },
    {
        name: 'Marina Bay Street Circuit',
        country: 'Singapore',
        city: 'Singapore',
        length: 4.940,
        numberOfLaps: 62,
        numberOfTurns: 19,
        recordTime: '1:34.486',
        recordDriver: 'Daniel Ricciardo',
        recordYear: 2013,
        image: '18.jpg'
    },
    {
        name: 'Circuit of the Americas',
        country: 'USA',
        city: 'Austin',
        length: 5.513,
        numberOfLaps: 56,
        numberOfTurns: 20,
        recordTime: '1:36.169',
        recordDriver: 'Charles Leclerc',
        recordYear: 2019,
        image: '19.jpg'
    },
    {
        name: 'Autodromo Hermanos Rodríguez',
        country: 'Mexico',
        city: 'Mexico City',
        length: 4.304,
        numberOfLaps: 71,
        numberOfTurns: 17,
        recordTime: '1:17.774',
        recordDriver: 'Valtteri Bottas',
        recordYear: 2021,
        image: '20.jpg'
    },
    {
        name: 'Interlagos (Autódromo José Carlos Pace)',
        country: 'Brazil',
        city: 'São Paulo',
        length: 4.309,
        numberOfLaps: 71,
        numberOfTurns: 15,
        recordTime: '1:11.010',
        recordDriver: 'Sergio Perez',
        recordYear: 2021,
        image: '21.jpg'
    },
    {
        name: 'Las Vegas Street Circuit',
        country: 'USA',
        city: 'Las Vegas',
        length: 6.201,
        numberOfLaps: 50,
        numberOfTurns: 17,
        recordTime: '1:34.876',
        recordDriver: 'Lando Norris',
        recordYear: 2023,
        image: '22.jpg'
    },
    {
        name: 'Lusail International Circuit',
        country: 'Qatar',
        city: 'Lusail',
        length: 5.419,
        numberOfLaps: 57,
        numberOfTurns: 16,
        recordTime: '1:22.384',
        recordDriver: 'Lando Norris',
        recordYear: 2024,
        image: '23.jpg'
    },
    {
        name: 'Yas Marina Circuit',
        country: 'United Arab Emirates',
        city: 'Abu Dhabi',
        length: 5.281,
        numberOfLaps: 58,
        numberOfTurns: 16,
        recordTime: '1:26.103',
        recordDriver: 'Kevin Magnussen',
        recordYear: 2024,
        image: '24.jpg'
    }
]
