export const circuits = [
    {
        id: 1,
        name: 'Albert Park Circuit',
        country: 'Australia',
        city: 'Melbourne',
        length: 5.278,
        numberOfLaps: 58,
        numberOfTurns: 14,
        recordTime: '1:19.813',
        recordDriver: 'Charles Leclerc',
        recordYear: 2024
    },
    {
        id: 2,
        name: 'Shanghai International Circuit',
        country: 'China',
        city: 'Shanghai',
        length: 5.451,
        numberOfLaps: 56,
        numberOfTurns: 16,
        recordTime: '1:32.238',
        recordDriver: 'Michael Schumacher',
        recordYear: 2004
    },
    {
        id: 3,
        name: 'Suzuka Circuit',
        country: 'Japan',
        city: 'Suzuka',
        length: 5.807,
        numberOfLaps: 53,
        numberOfTurns: 18,
        recordTime: '1:30.965',
        recordDriver: 'Kimi Antonelli',
        recordYear: 2025
    },
    {
        id: 4,
        name: 'Miami International Autodrome',
        country: 'USA',
        city: 'Miami',
        length: 5.412,
        numberOfLaps: 57,
        numberOfTurns: 19,
        recordTime: '1:29.708',
        recordDriver: 'Max Verstappen',
        recordYear: 2023
    },
    {
        id: 5,
        name: 'Circuit Gilles Villeneuve',
        country: 'Canada',
        city: 'Montreal',
        length: 4.361,
        numberOfLaps: 70,
        numberOfTurns: 14,
        recordTime: '1:13.078',
        recordDriver: 'Valtteri Bottas',
        recordYear: 2019
    },
    {
        id: 6,
        name: 'Circuit de Monaco',
        country: 'Monaco',
        city: 'Monte Carlo',
        length: 3.337,
        numberOfLaps: 78,
        numberOfTurns: 19,
        recordTime: '1:12.909',
        recordDriver: 'Lewis Hamilton',
        recordYear: 2021
    },
    {
        id: 7,
        name: 'Circuit de Catalunya',
        country: 'Spain',
        city: 'Barcelona',
        length: 4.657,
        numberOfLaps: 66,
        numberOfTurns: 16,
        recordTime: '1:15.743',
        recordDriver: 'Oscar Piastri',
        recordYear: 2025
    },
    {
        id: 8,
        name: 'Red Bull Ring',
        country: 'Austria',
        city: 'Spielberg',
        length: 4.326,
        numberOfLaps: 71,
        numberOfTurns: 10,
        recordTime: '1:07.924',
        recordDriver: 'Oscar Piastri',
        recordYear: 2025
    },
    {
        id: 9,
        name: 'Silverstone Circuit',
        country: 'United Kingdom',
        city: 'Silverstone',
        length: 5.891,
        numberOfLaps: 52,
        numberOfTurns: 18,
        recordTime: '1:27.097',
        recordDriver: 'Max Verstappen',
        recordYear: 2020
    },
    {
        id: 10,
        name: 'Circuit de Spa-Francorchamps',
        country: 'Belgium',
        city: 'Spa',
        length: 7.004,
        numberOfLaps: 44,
        numberOfTurns: 19,
        recordTime: '1:44.701',
        recordDriver: 'Sergio Perez',
        recordYear: 2024
    },
    {
        id: 11,
        name: 'Hungaroring',
        country: 'Hungary',
        city: 'Budapest',
        length: 4.381,
        numberOfLaps: 70,
        numberOfTurns: 14,
        recordTime: '1:16.627',
        recordDriver: 'Lewis Hamilton',
        recordYear: 2020
    },
    {
        id: 12,
        name: 'Circuit Zandvoort',
        country: 'Netherlands',
        city: 'Zandvoort',
        length: 4.259,
        numberOfLaps: 72,
        numberOfTurns: 14,
        recordTime: '1:11.097',
        recordDriver: 'Lewis Hamilton',
        recordYear: 2021
    },
    {
        id: 13,
        name: 'Autodromo Nazionale Monza',
        country: 'Italy',
        city: 'Monza',
        length: 5.793,
        numberOfLaps: 53,
        numberOfTurns: 11,
        recordTime: '1:20.901',
        recordDriver: 'Lando Norris',
        recordYear: 2025
    },
    {
        id: 14,
        name: 'Circuito de Madring',
        country: 'Spain',
        city: 'Madrid',
        length: 5.416,
        numberOfLaps: 57,
        numberOfTurns: 22,
        recordTime: 'N/A',
        recordDriver: 'N/A',
        recordYear: 'N/A'
    },
    {
        id: 15,
        name: 'Baku City Circuit',
        country: 'Azerbaijan',
        city: 'Baku',
        length: 6.003,
        numberOfLaps: 51,
        numberOfTurns: 20,
        recordTime: '1:43.009',
        recordDriver: 'Charles Leclerc',
        recordYear: 2019
    },
    {
        id: 16,
        name: 'Marina Bay Street Circuit',
        country: 'Singapore',
        city: 'Singapore',
        length: 4.927,
        numberOfLaps: 62,
        numberOfTurns: 19,
        recordTime: '1:33.808',
        recordDriver: 'Lewis Hamilton',
        recordYear: 2025
    },
    {
        id: 17,
        name: 'Circuit of the Americas',
        country: 'USA',
        city: 'Austin',
        length: 5.513,
        numberOfLaps: 56,
        numberOfTurns: 20,
        recordTime: '1:36.169',
        recordDriver: 'Charles Leclerc',
        recordYear: 2019
    },
    {
        id: 18,
        name: 'Autodromo Hermanos Rodríguez',
        country: 'Mexico',
        city: 'Mexico City',
        length: 4.304,
        numberOfLaps: 71,
        numberOfTurns: 17,
        recordTime: '1:17.774',
        recordDriver: 'Valtteri Bottas',
        recordYear: 2021
    },
    {
        id: 19,
        name: 'Autódromo José Carlos Pace',
        country: 'Brazil',
        city: 'São Paulo',
        length: 4.309,
        numberOfLaps: 71,
        numberOfTurns: 15,
        recordTime: '1:10.540',
        recordDriver: 'Valtteri Bottas',
        recordYear: 2018
    },
    {
        id: 20,
        name: 'Las Vegas Street Circuit',
        country: 'USA',
        city: 'Las Vegas',
        length: 6.201,
        numberOfLaps: 50,
        numberOfTurns: 17,
        recordTime: '1:33.365',
        recordDriver: 'Max Verstappen',
        recordYear: 2025
    },
    {
        id: 21,
        name: 'Lusail International Circuit',
        country: 'Qatar',
        city: 'Lusail',
        length: 5.419,
        numberOfLaps: 57,
        numberOfTurns: 16,
        recordTime: '1:22.384',
        recordDriver: 'Lando Norris',
        recordYear: 2024
    },
    {
        id: 22,
        name: 'Yas Marina Circuit',
        country: 'United Arab Emirates',
        city: 'Abu Dhabi',
        length: 5.281,
        numberOfLaps: 58,
        numberOfTurns: 16,
        recordTime: '1:25.637',
        recordDriver: 'Kevin Magnussen',
        recordYear: 2024
    }
]